"""Add attribute is_verified to user

Revision ID: 07a28872e450
Revises: a0f7e7a7a46d
Create Date: 2026-08-19 00:31:26.351217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a28872e450'
down_revision: Union[str, Sequence[str], None] = 'a0f7e7a7a46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
