"""add product start and end time

Revision ID: 17a6433c9ec3
Revises: e36c85fc5291
Create Date: 2026-07-24 00:54:22.167238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a6433c9ec3'
down_revision: Union[str, Sequence[str], None] = 'e36c85fc5291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('starts_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('ends_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'ends_at')
    op.drop_column('product', 'starts_at')
    # ### end Alembic commands ###
