"""add sale type and buy now price

Revision ID: 1ca4a4759481
Revises: 17a6433c9ec3
Create Date: 2026-07-24 01:00:54.341887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca4a4759481'
down_revision: Union[str, Sequence[str], None] = '17a6433c9ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sale_type', sa.Enum('AUCTION', 'BUY_NOW', 'BOTH', name='saletype', native_enum=False), nullable=False))
    op.add_column('product', sa.Column('buy_now_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'buy_now_price')
    op.drop_column('product', 'sale_type')
    # ### end Alembic commands ###
