"""add buyer_id to product to identify win by buying the product

Revision ID: 22cdfeb87539
Revises: 07a28872e450
Create Date: 2026-09-13 21:43:03.974781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cdfeb87539'
down_revision: Union[str, Sequence[str], None] = '07a28872e450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['buyer_id'], ['id'])
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'buyer_id')
    # ### end Alembic commands ###
