"""add table watchlist, add delete cascade in bid

Revision ID: 41a0dbdf26ca
Revises: 65757cd0681c
Create Date: 2026-08-06 12:15:47.451728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a0dbdf26ca'
down_revision: Union[str, Sequence[str], None] = '65757cd0681c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_follow', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'product_id', name='uq_user_product_watchlist')
    )
    op.drop_constraint(op.f('bid_product_id_fkey'), 'bid', type_='foreignkey')
    op.drop_constraint(op.f('bid_bidder_id_fkey'), 'bid', type_='foreignkey')
    op.create_foreign_key(None, 'bid', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bid', 'user', ['bidder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.create_foreign_key(op.f('bid_bidder_id_fkey'), 'bid', 'user', ['bidder_id'], ['id'])
    op.create_foreign_key(op.f('bid_product_id_fkey'), 'bid', 'product', ['product_id'], ['id'])
    op.drop_table('watchlist')
    # ### end Alembic commands ###
