"""add user attribute public last name

Revision ID: 5975a5d5a941
Revises: 41a0dbdf26ca
Create Date: 2026-08-07 09:40:10.972372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5975a5d5a941'
down_revision: Union[str, Sequence[str], None] = '41a0dbdf26ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_last_name', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_last_name')
    # ### end Alembic commands ###
