"""add min_bid attribute to product

Revision ID: 65757cd0681c
Revises: a8a17795e293
Create Date: 2026-08-04 11:22:05.437297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65757cd0681c'
down_revision: Union[str, Sequence[str], None] = 'a8a17795e293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('min_bid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'min_bid')
    # ### end Alembic commands ###
