"""fix user - group relationship

Revision ID: 7c8321d95f00
Revises: ab9ca7af1025
Create Date: 2026-07-30 13:56:03.103100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8321d95f00'
down_revision: Union[str, Sequence[str], None] = 'ab9ca7af1025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'status')
    # ### end Alembic commands ###
