"""fix cascade delete to product_image

Revision ID: 7f46db4efef8
Revises: 27cb715163b5
Create Date: 2026-09-30 10:40:45.577766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f46db4efef8'
down_revision: Union[str, Sequence[str], None] = '27cb715163b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_image_product_id_fkey'), 'product_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.create_foreign_key(op.f('product_image_product_id_fkey'), 'product_image', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
