"""fix: add new order status processing

Revision ID: a6a44ae33097
Revises: c9b20585b2e3
Create Date: 2026-10-01 22:11:54.373464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6a44ae33097'
down_revision: Union[str, Sequence[str], None] = 'c9b20585b2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'EXPIRED', 'CANCELLED', name='orderstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'PAID', 'EXPIRED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
