"""add group as nullable FK to products

Revision ID: ab9ca7af1025
Revises: c5ea6618762c
Create Date: 2026-07-30 12:34:04.364649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9ca7af1025'
down_revision: Union[str, Sequence[str], None] = 'c5ea6618762c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_owner_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'product', 'user', ['created_by_id'], ['id'])
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_owner_id_fkey'), 'product', 'user', ['owner_id'], ['id'])
    op.drop_column('product', 'group_id')
    op.drop_column('product', 'created_by_id')
    # ### end Alembic commands ###
