"""add product big_preview option

Revision ID: bfe1de89b46f
Revises: 1ca4a4759481
Create Date: 2026-07-27 22:27:39.504960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe1de89b46f'
down_revision: Union[str, Sequence[str], None] = '1ca4a4759481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('big_preview', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'big_preview')
    # ### end Alembic commands ###
