"""Delete unecessary attribute sale_type in product

Revision ID: ce734469bc5a
Revises: feb2681a9c38
Create Date: 2026-08-18 11:15:42.184123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce734469bc5a'
down_revision: Union[str, Sequence[str], None] = 'feb2681a9c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sale_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sale_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
