"""alter user attribute public last name to not null

Revision ID: d602f60eaa8a
Revises: 5975a5d5a941
Create Date: 2026-08-07 09:45:31.996274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd602f60eaa8a'
down_revision: Union[str, Sequence[str], None] = '5975a5d5a941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'public_last_name',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'public_last_name',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
