"""add delivery info to order

Revision ID: f2a2d7014b85
Revises: 84f62357c05c
Create Date: 2026-10-01 20:49:14.430411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a2d7014b85'
down_revision: Union[str, Sequence[str], None] = '84f62357c05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_method', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('shipping_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_address')
    op.drop_column('order', 'delivery_method')
    # ### end Alembic commands ###
